checklist: $HOME/SystemSetup.md

install_groups:
  - group: Core Dependencies
    optional: false
    software:
      - name: Xcode
        artifact: /Applications/Xcode.app
        install:
          - mas: "497799835"
        configure:
          - ignore_errors: true
          - run: sudo xcode-select --install
          - run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          - run: sudo xcodebuild -runFirstLaunch
        checklist:
          - Accept Xcode license agreement
          - Install additional components when prompted

      - name: Homebrew
        artifact: $BREW/bin/brew
        install:
          - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          - run: brew tap homebrew/autoupdate
          - run: brew autoupdate start 86400 --cleanup

      - artifact: $BREW/Cellar/brew-caveats
        install:
          - run: brew install rafaelgarrido/homebrew-caveats/brew-caveats

      - artifact: $BREW/bin/brew-gem
        install:
          - brew: brew-gem

      - artifact: $BREW/bin/brew-gomod
        install:
          - brew: cdzombak/gomod/brew-gomod

      - name: Mac App Store CLI
        artifact: $BREW/bin/mas
        install:
          - brew: mas

      - artifact: $BREW/bin/pipx
        install:
          - brew: pipx
